# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Interesting Facts',  url: 'facts'}
- {name: 'Learning Resources', url: 'resources'}
- {name: 'Sample Posts',       url: 'sample-posts'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:bartuakyurek@outlook.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'


related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
